Surfer.create(surfername: "Miki Dora", email: "Dora@malibu.com", password: "12345")
Surfer.create(surfername: "Mick Fanning", email: "mfan@prosurfer.com", password: "12345")
Surfer.create(surfername: "Kelly Slater", email: "kslate@surfranch.com", password: "12345")
Surfer.create(surfername: "Wiggy Owens", email: "wiggo@oldschool.com", password: "12345")
Surfer.create(surfername: "Pitchouli Bob", email: "bob@pitchouli.com", password: "12345")
Surfer.create(surfername: "Ashley Stevens", email: "ashleystevens@wahoo.com", password: "12345")
Surfer.create(surfername: "Slugo", email: "sluggy@email.com", password: "12345")
Surfer.create(surfername: "Phil Edwards", email: "philly@eddy.com", password: "12345")
Surfer.create(surfername: "Nat Young", email: "nat@young.org", password: "12345")
Surfer.create(surfername: "Bethany Hamilton", email: "bethh@soulsurfer.com", password: "12345")
Surfer.create(surfername: "Jerricho Poppler", email: "jerrypop@jerrypop.com", password: "12345")
Surfer.create(surfername: "Lance Burkhart", email: "shady@surfer.com", password: "12345")

LogEntry.create(surf_spot: "Malibu", swell_size: "5ft", swell_direction: "SW", conditions: "Side shore wind", wave_count: "100", content: "I'm the king of malibu! no hodad can top this hotdogger! I surfed every single wave in the curl all day!", image_url: "/images/malibu2.jpg", date: "summer 1960", surfer_id: 1)
LogEntry.create(surf_spot: "Bells Beach", swell_size: "", swell_direction: "", conditions: "", wave_count: "", content: "Crikey, what a blast! I got so tubed! You wouldn't believe it, mate!", image_url: "/images/bellsbeach.jpg", date: "6/3/2011", surfer_id: 2)
LogEntry.create(surf_spot: "Pipeline", swell_size: "Double Overhead", swell_direction: "Northwest", conditions: "Clean", wave_count: "20-30", content: "What can I say? Best waves of my life? Always trying to get that epic sesh!", image_url: "/images/pipeline.jpg", date: "", surfer_id: 3)
LogEntry.create(surf_spot: "Lower Trestles", swell_size: "", swell_direction: "", conditions: "", wave_count: "5", content: "It got really packed! Even though I'm the most famous surfer in the world I still have to fight for waves!", image_url: "/images/trestles.jpg", date: "November 10, 2016", surfer_id: 3)
LogEntry.create(surf_spot: "Surf Ranch", swell_size: "", swell_direction: "", conditions: "Mechanical", wave_count: "", content: "Sometimes you just have to build the perfect wave and fense it in to get waves to yourself.", image_url: "/images/surfranchkellyslater.jpg", date: "", surfer_id: 3)
LogEntry.create(surf_spot: "Seal Beach Pier", swell_size: "Massive", swell_direction: "", conditions: "Stormy", wave_count: "Just this one!", content: "The storm broke the pier in half! I paddle out and got this one from the boneyard! One and done!", image_url: "/images/seal_pier.jpg", date: "Febuary 11, 1983", surfer_id: 4)
LogEntry.create(surf_spot: "Malibu", swell_size: "Huge", swell_direction: "south southwest", conditions: "decent", wave_count: "10", content: "Hurricane Marie was pumpin, man! Could believe have solid the waves were. Oh, man. You should have been there!", image_url: "/images/malibu3.jpg", date: "Aug 2014", surfer_id: 5)
LogEntry.create(surf_spot: "Seal Beach northside", swell_size: "chest high", swell_direction: "west", conditions: "cold and clean winter morning", wave_count: "8(all i need)", content: "OMG! I love surfing seal when it's that good! So fun!", image_url: "/images/seal_beach_pier.jpg", date: "Dec 14, 2014", surfer_id: 6)
LogEntry.create(surf_spot: "SB pier", swell_size: "", swell_direction: "", conditions: "Far out", wave_count: "?", content: "Man, I got some humdingers and a couple of whoppers! One wave was a doozy!", image_url: "/images/sb_pier.jpg", date: "January 2009", surfer_id: 7)
LogEntry.create(surf_spot: "Waimea Bay", swell_size: "Big as a barn", swell_direction: "", conditions: "", wave_count: "35", content: "Well, the surf session was really swell. Ha, see what I did there?", image_url: "/images/waimea_Bay.jpg", date: "winter of 1965", surfer_id: 8)
LogEntry.create(surf_spot: "Bells Beach", swell_size: "", swell_direction: "", conditions: "", wave_count: "", content: "Damn! It was epic! So epic in fact that I forgot my camera! Oh well, you do believe me that it was epic right?", image_url: "", date: "5-3-1975", surfer_id: 9)
LogEntry.create(surf_spot: "Teahupoo", swell_size: "SSSOOOOO BBBIIIIGGGG!!!", swell_direction: "SSW and S mix", conditions: "GREAT!", wave_count: "", content: "After locking in Teahupoo like I did today the world will know I can hold my own in the world of Surfing!", image_url: "/images/teahupoo.jpg", date: "", surfer_id: 10)
LogEntry.create(surf_spot: "Trestles", swell_size: "Chest high", swell_direction: "", conditions: "kinda frothy but lots of sun", wave_count: "21", content: "Wow! Do I look great! I love that bathing suit! I was on the nose and carving the curl all day!", image_url: "/images/jerricho.jpg", date: "June 1979", surfer_id: 11)
LogEntry.create(surf_spot: "Malibu", swell_size: "", swell_direction: "", conditions: "", wave_count: "", content: "For all who were out surfing, I have a message. Don't Snake Me!", image_url: "/images/malibu.jpg", date: "1959", surfer_id: 12)
